kind: Service
apiVersion: v1
metadata:
  name: fastapi-{{ .Values.environment }}-service
  labels:
    app: fastapi-{{ .Values.environment }}
  namespace: {{ .Values.namespace | default "app1" }}
  annotations:
    # 1. Use the recommended AWS Load Balancer Controller
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    
    # 2. Force the LB to be accessible from the internet
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    
    # 3. Use 'ip' mode for better performance with AWS CNI
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  selector:
    app: fastapi-{{ .Values.environment }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.deployment.port | default 8000 }}
      nodePort: {{ .Values.service.nodePort | default 30080 }}
      name: http