apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team1-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/NaveenKumar-Y/kubernetes
    targetRevision: HEAD
    path: argoCD/platform_gitops/applications/team1
   
  destination:
    server: https://kubernetes.default.svc
    namespace: geocentric

  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
